# Float Assignments

** All the outputs mentioned in this executable ipynb file are executed at my end

---

Q.1) Declare a float value and store it in a variable.
Check the type and print the id of the same.

In [1]:
float1 = 2.3
id(float1)

# Output :
# 138498857212784

138498857212784

---

Q.2) Arithmetic Operations on float

Take two different float values. Store them in two different variables.

Do below operations on them:-
* Find sum of both numbers
* Find difference between them
* Find the product of both numbers.
* Find value after dividing first num with second number
* Find the remainder after dividing first number with second number
* Find the quotient after dividing first number with second number
* Find the result of the first num to the power of the second number.

In [2]:
float2 = 3.5
float3 = 5.6
sum = float2 + float3
difference = float2 - float3
product = float2 * float3
floorDivision = float2 // float3
remainder = float2 % float3
quotient = float2 / float3
exponential = float2 ** float3
print("Sum : {}".format(sum))
print("Difference : {}".format(difference))
print("Product : {}".format(product))
print("Floor Division : {}".format(floorDivision))
print("Remainder : {}".format(remainder))
print("Quotient : {}".format(quotient))
print("Exponential : {}".format(exponential))

# Output :

# Sum : 9.1
# Difference : -2.0999999999999996
# Product : 19.599999999999998
# Floor Division : 0.0
# Remainder : 3.5
# Quotient : 0.625
# Exponential : 1113.7328982650954

Sum : 9.1
Difference : -2.0999999999999996
Product : 19.599999999999998
Floor Division : 0.0
Remainder : 3.5
Quotient : 0.625
Exponential : 1113.7328982650954

---

Q.3) Comparison Operators on float

Take two different float values. Store them in two different variables.

Do below operations on them:-

Compare the two numbers with below operator:-

* Greater than, '>'
* Smaller than, '<'
* Greater than or equal to, '>='
* Less than or equal to, '<='

Observe their output(return type should be boolean)

In [3]:
float4 = 6.6
float5 = 9.8
print("float4 > float5: {}".format(float4 > float5))
print("float4 < float5: {}".format(float4 < float5))
print("float4 >= float5 : {}".format(float4 >= float5))
print("float4 <= float5 : {}".format(float4 <= float5))

# Output :

# float4 > float5: False
# float4 < float5: True
# float4 >= float5 : False
# float4 <= float5 : True

float4 > float5: False
float4 < float5: True
float4 >= float5 : False
float4 <= float5 : True

---
Q.4) Equality Operator

Take two different float values.
Store them in two different variables.

Equate them using equality operators (==, !=).
Observe the output(return type should be boolean)

In [5]:
float6 = 45.6
float7 = 33.2
print("float6 == float7 : {}".format(float6 == float7))
print("float6 != float7 : {}".format(float6 != float7))

# Output :

# float6 == float7 : False
# float6 != float7 : TrueO

float6 == float7 : False
float6 != float7 : True

---

Q.5) Logical operators

Observe the output of below code. Cross check the output manually.

* print(10.20 and 20.30) #both are true and second value taken >Output is 20.3
* print(0.0 and 20.30) #First is false so first value
taken->Output is 0.0
* print(20.30 and 0.0) #Goes to till second and second value is
false so second is taken>Output is 0.0
* print(0.0 and 0.0) #First is false so first value is
taken->Output is 0.0
* print(10.20 or 20.30) #First is True so first value is
taken>Output is 10.2
* print(0.0 or 20.30) #Goes to till second and second is true
second value is taken->Output is 20.3
* print(20.30 or 0.0) #First is True so first value is
taken->Output is 20.3
* print(0.0 or 0.0) #Goes to till second and second is also
false and second value is taken>Output is 0.0
* print(not 10.20) #-Not of true is false->Output is False
* print(not 0.0) #Not of false is True>Output is True

In [6]:
print("10.20 and 20.30 : {}".format(10.20 and 20.30))
print("0.0 and 20.30 : {}".format(0.0 and 20.30))
print("20.30 and 0.0 : {}".format(20.30 and 0.0))
print("0.0 and 0.0 : {}\n".format(0 and 0.0))

print("10.20 or 20.30 : {}".format(10.20 or 20.30))
print("0.0 or 20.30 : {}".format(0.0 or 20.30))
print("20.30 or 0.0 : {}".format(20.30 or 0.0))
print("0.0 or 0.0 : {}\n".format(0 or 0.0))

print("not 10.20 : {}".format(not 10.20))
print("not 0.0 : {}".format(not 0.0))

# Output :

# 10.20 and 20.30 : 20.3  // and operator returns the second operand if the first operand is false value
# 0.0 and 20.30 : 0.0
# 20.30 and 0.0 : 0.0
# 0.0 and 0.0 : 0

# 10.20 or 20.30 : 10.2 // or operator returns the first operand if the first operand is true value
# 0.0 or 20.30 : 20.3
# 20.30 or 0.0 : 20.3
# 0.0 or 0.0 : 0.0

# not 10.20 : False // not operator returns the opposite of the operand
# not 0.0 : True

10.20 and 20.30 : 20.3
0.0 and 20.30 : 0.0
20.30 and 0.0 : 0.0
0.0 and 0.0 : 0

10.20 or 20.30 : 10.2
0.0 or 20.30 : 20.3
20.30 or 0.0 : 20.3
0.0 or 0.0 : 0.0

not 10.20 : False
not 0.0 : True

---

Q.6) What is the output of expression inside print statement. Cross check before running the program.

a = 10.20                       
b = 10.20                                           
print(a is b) #True or False? True 10.20<256                        
print(a is not b) #True or False? False

Why the Id of float values are different when the same value is
assigned to two different variables.

ex: a = 10.5 b=10.5. but id will be same if I assign the variable
having float i.e. a=c then both a and c's Id are same

In [9]:
a = 10.20
b = 10.20
print(a is b)
print(a is not b)

# Output :

# False
# True

# Object reusability concept is not applicable to float values

138498236384240
138498857222064
False
True

---

Q.7) Bitwise operation is not applicable between instances of float.

Why the Id of float values are different when the same value is
assigned to two different variables?

----> Object reusability concept is not applicable on float values.

---

Q.8) Membership operation

in, not in are two membership operators and it returns boolean value
* print('2.7' in 'Python2.7.8') #True
* print(10.20 in [10,10.20,10+20j,'Python']) #True
* print(10.20 in (10,10.20,10+20j,'Python')) # True
* print(20.30 in {1,20.30,30+40j}) # True
* print(2.3 in {1:100, 2.3:200, 30+40j:300}) # True
* print(10 in range(20)) # True

In [10]:
print('2.7' in 'Python2.7.8')
print(10.20 in [10,10.20,10+20j,'Python'])
print(10.20 in (10,10.20,10+20j,'Python'))
print(20.30 in {1,20.30,30+40j})
print(2.3 in {1:100, 2.3:200, 30+40j:300})
print(10 in range(20))

# Output :

# True
# True
# True
# True
# True
# True

# Membership operator return True if given value exists in the given sequence

True
True
True
True
True
True